name: DataMiner CICD Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CI:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Automation Master Workflow.yml@main
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: SkylineCommunications_NBCU-AS-NevionVideoIPath
    secrets:
      # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
      api-key: ${{ secrets.DATAMINER_TOKEN }}
      sonarCloudToken: ${{ secrets.SONAR_TOKEN }}

  LAB_CD:
    name: LAB Deployment
    needs: CI
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#push_lab') }}
    steps:
        - uses: actions/checkout@v3
        - name: Set up NuGet
          uses: nuget/setup-nuget@v2.0.1     
        - name: NuGet restore solution
          run: nuget restore "AutomationScript.sln" -OutputDirectory ${{ github.workspace }}/packages
        - name: Skyline DataMiner Deploy Action
          # You may pin to the exact commit or the version.
          # uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@9b6581af0865af90b24bc5a0a0369648892ac48f
          uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v3.0.0
          with:
            # The API-key generated in the DCP Admin app as authentication for a certain Organization, saved in a GitHub secret
            api-key: ${{ secrets.DATAMINER_TOKEN }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
            solution-path: ./AutomationScript.sln
            artifact-name: ${{ github.repository }} ${{ github.ref_name }}_B${{ github.run_number }}
            build-number: ${{ github.run_number }}
            agent-destination-id: ${{ secrets.LAB_AGENT_ID }}
            
            
          
          
        
  # # Optional 0 or More CD Jobs as needed
  # CD:
  #   if: github.ref_type == 'tag'
  #   environment: production
  #   name: CD
  #   runs-on: ubuntu-latest
  #   needs: CI

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Skyline DataMiner Deploy Action
  #       uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
  #       with:
  #         # Stage deploy
  #         stage: Deploy
  #         # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
  #         api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
  #         # Id of the uploaded artifact
  #         artifact-id: ${{ needs.CI.outputs.artifact-id }}
