name: DataMiner CICD Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CI:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Automation Master Workflow.yml@main
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: SkylineCommunications_NBCU-AS-NevionVideoIPath
    secrets:
      # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
      api-key: ${{ secrets.DATAMINER_TOKEN }}
      sonarCloudToken: ${{ secrets.SONAR_TOKEN }}

  LAB_CD:
    runs-on: windows-latest
    needs: CI
    if: ${{ contains(github.event.head_commit.message, '#push_lab') }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Package Creation
      run: dotnet tool install -g Skyline.DataMiner.CICD.Tools.Packager
    - name: Install DataMiner Deploy
      run: dotnet tool install -g Skyline.DataMiner.CICD.Tools.DataMinerDeploy
    - name: Create Protocol Package
      run: dataminer-package-create dmapp "${{ github.workspace }}" --name  "Nevion_Scripts" --output "${{ github.workspace }}\\_PackageResults"
    - name: Direct Agent Deployment
      run: dataminer-package-deploy from-artifact --path-to-artifact "${{ github.workspace }}\\_PackageResults\\Nevion_Scripts.dmapp" --dm-server-location "${{ secrets.LAB_SERVER_LOCATION }}" --dm-user "${{ secrets.LAB_DATAMINER_USER }}" --dm-password "${{ secrets.LAB_DATAMINER_PASSWORD }}"
        
  # # Optional 0 or More CD Jobs as needed
  # CD:
  #   if: github.ref_type == 'tag'
  #   environment: production
  #   name: CD
  #   runs-on: ubuntu-latest
  #   needs: CI

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Skyline DataMiner Deploy Action
  #       uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
  #       with:
  #         # Stage deploy
  #         stage: Deploy
  #         # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
  #         api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
  #         # Id of the uploaded artifact
  #         artifact-id: ${{ needs.CI.outputs.artifact-id }}
